<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketBook.Application\MarketBook.Application.csproj" />
    <ProjectReference Include="..\MarketBook.Domain\MarketBook.Domain.csproj" />
  </ItemGroup>

</Project>
