// <auto-generated />
using System;
using MarketBook.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketBook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908183906_AddPortfolioBaseCurrencyAndFxRate")]
    partial class AddPortfolioBaseCurrencyAndFxRate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketBook.Domain.Calendar.Aggregates.TradingCalendar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("WeekendDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "Year")
                        .IsUnique()
                        .HasDatabaseName("UX_TradingCalendars_Market_Year");

                    b.ToTable("TradingCalendars", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Country.Aggregates.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Currency.Aggregates.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Currency.Aggregates.FxRate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("BaseCurrencyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QuoteCurrencyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(38,10)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("UX_FxRates_Base_Quote_Date");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "RateDate", "CreatedOn")
                        .HasDatabaseName("IX_FxRates_Latest");

                    b.ToTable("FxRates", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Exchange.Aggregates.Exchange", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CountryId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Exchanges", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Instrument.Aggregates.Instrument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("[Isin] IS NOT NULL");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Investor.Aggregates.Investor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Investors_FullName");

                    b.ToTable("Investors", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Listing.Aggregates.Listing", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset?>("ActivatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<byte>("PricePrecision")
                        .HasColumnType("tinyint");

                    b.Property<string>("QuoteCurrencyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("decimal(38,28)");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Listings_Instrument_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("VenueId", "TradingSymbol")
                        .IsUnique()
                        .HasDatabaseName("UX_Listings_Venue_TradingSymbol");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Market.Aggregates.Market", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExchangeId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExchangeId");

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.DailyTradeStatistics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("MarketCapitalization")
                        .HasColumnType("decimal(38,2)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TradeValue")
                        .HasColumnType("decimal(38,2)");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "TradingDate")
                        .IsUnique()
                        .HasDatabaseName("UX_DailyTradeStatistics_Listing_TradingDate");

                    b.ToTable("DailyTradeStatistics", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.IntradayPriceTick", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,6)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "TradingDate", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_IntradayPriceTicks_Listing_TradingDate_Sequence");

                    b.HasIndex("ListingId", "TradingDate", "OccurredAt", "SequenceNumber")
                        .HasDatabaseName("IX_IntradayPriceTicks_Listing_TradingDate_OccurredAt_Sequence");

                    b.ToTable("IntradayPriceTicks", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.MarketPrice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("PreviousClosePrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("decimal(38,6)");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("decimal(38,6)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "TradingDate")
                        .IsUnique()
                        .HasDatabaseName("UX_MarketPrices_Listing_TradingDate");

                    b.ToTable("MarketPrices", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.OrderBookSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "TradingDate", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderBookSnapshots_Listing_TradingDate_Sequence");

                    b.HasIndex("ListingId", "TradingDate", "CapturedAt", "SequenceNumber")
                        .HasDatabaseName("IX_OrderBookSnapshots_Listing_TradingDate_CapturedAt_Sequence");

                    b.ToTable("OrderBookSnapshots", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.Portfolio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("BaseCurrencyId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvestorId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId")
                        .HasDatabaseName("IX_Portfolios_BaseCurrencyId");

                    b.HasIndex("InvestorId")
                        .HasDatabaseName("IX_Portfolios_InvestorId");

                    b.HasIndex("InvestorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Portfolios_InvestorId_Name");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.PortfolioCashTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_PortfolioCashTransactions_Reference")
                        .HasFilter("[ReferenceType] IS NOT NULL AND [ReferenceId] IS NOT NULL");

                    b.HasIndex("PortfolioId", "OccurredOn", "Id")
                        .HasDatabaseName("IX_PortfolioCashTransactions_Portfolio_OccurredOn_Id");

                    b.HasIndex("PortfolioId", "CurrencyId", "OccurredOn", "Id")
                        .HasDatabaseName("IX_PortfolioCashTransactions_Portfolio_Currency_OccurredOn_Id");

                    b.ToTable("PortfolioCashTransactions", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.PortfolioTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("BrokerFee")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<decimal>("ClearingFee")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<decimal>("Commission")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("ExchangeFee")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<DateTimeOffset>("ExecutedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("OtherFees")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<decimal>("Price")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ListingId");

                    b.HasIndex("PortfolioId", "ExecutedOn", "Id")
                        .HasDatabaseName("IX_PortfolioTransactions_Portfolio_ExecutedOn_Id");

                    b.HasIndex("PortfolioId", "ListingId", "ExecutedOn", "Id")
                        .HasDatabaseName("IX_PortfolioTransactions_Portfolio_Listing_ExecutedOn_Id");

                    b.ToTable("PortfolioTransactions", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Venue.Aggregates.Venue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MarketId");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("MarketBook.Domain.Calendar.Aggregates.TradingCalendar", b =>
                {
                    b.HasOne("MarketBook.Domain.Market.Aggregates.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("MarketBook.Domain.Calendar.Entities.CalendarDateException", "DateExceptions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsHalfDay")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsHoliday")
                                .HasColumnType("bit");

                            b1.Property<string>("TradingCalendarId")
                                .IsRequired()
                                .HasColumnType("varchar(26)");

                            b1.HasKey("Id");

                            b1.HasIndex("TradingCalendarId", "Date")
                                .IsUnique()
                                .HasDatabaseName("UX_TradingCalendarDateExceptions_Calendar_Date");

                            b1.ToTable("TradingCalendarDateExceptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TradingCalendarId");
                        });

                    b.OwnsMany("MarketBook.Domain.Calendar.Entities.TradingSession", "Sessions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("ClosesAt")
                                .HasColumnType("time");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("OpensAt")
                                .HasColumnType("time");

                            b1.Property<string>("TradingCalendarId")
                                .IsRequired()
                                .HasColumnType("varchar(26)");

                            b1.HasKey("Id");

                            b1.HasIndex("TradingCalendarId", "DayOfWeek")
                                .IsUnique()
                                .HasDatabaseName("UX_TradingCalendarSessions_Calendar_Day");

                            b1.ToTable("TradingCalendarSessions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TradingCalendarId");
                        });

                    b.Navigation("DateExceptions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MarketBook.Domain.Currency.Aggregates.FxRate", b =>
                {
                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.Listing.Aggregates.Listing", b =>
                {
                    b.HasOne("MarketBook.Domain.Instrument.Aggregates.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Venue.Aggregates.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.Market.Aggregates.Market", b =>
                {
                    b.HasOne("MarketBook.Domain.Exchange.Aggregates.Exchange", null)
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.DailyTradeStatistics", b =>
                {
                    b.HasOne("MarketBook.Domain.Listing.Aggregates.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.IntradayPriceTick", b =>
                {
                    b.HasOne("MarketBook.Domain.Listing.Aggregates.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.MarketPrice", b =>
                {
                    b.HasOne("MarketBook.Domain.Listing.Aggregates.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.MarketData.Aggregates.OrderBookSnapshot", b =>
                {
                    b.HasOne("MarketBook.Domain.Listing.Aggregates.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("MarketBook.Domain.MarketData.Entities.OrderBookSnapshotLevel", "Levels", b1 =>
                        {
                            b1.Property<string>("OrderBookSnapshotId")
                                .HasMaxLength(26)
                                .IsUnicode(false)
                                .HasColumnType("varchar(26)");

                            b1.Property<int>("Level")
                                .HasColumnType("int");

                            b1.Property<int?>("AskOrderCount")
                                .HasColumnType("int");

                            b1.Property<decimal?>("AskPrice")
                                .HasColumnType("decimal(38,6)");

                            b1.Property<long?>("AskVolume")
                                .HasColumnType("bigint");

                            b1.Property<int?>("BidOrderCount")
                                .HasColumnType("int");

                            b1.Property<decimal?>("BidPrice")
                                .HasColumnType("decimal(38,6)");

                            b1.Property<long?>("BidVolume")
                                .HasColumnType("bigint");

                            b1.HasKey("OrderBookSnapshotId", "Level");

                            b1.ToTable("OrderBookSnapshotLevels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderBookSnapshotId");
                        });

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.Portfolio", b =>
                {
                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketBook.Domain.Investor.Aggregates.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.PortfolioCashTransaction", b =>
                {
                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Portfolio.Aggregates.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.Portfolio.Aggregates.PortfolioTransaction", b =>
                {
                    b.HasOne("MarketBook.Domain.Currency.Aggregates.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Listing.Aggregates.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketBook.Domain.Portfolio.Aggregates.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketBook.Domain.Venue.Aggregates.Venue", b =>
                {
                    b.HasOne("MarketBook.Domain.Market.Aggregates.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
